# Generated by Django 5.0.1 on 2024-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_title_posts_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='caption',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
